// Copies design tokens, icons and fonts from npm packages into the theme.
// Run `npm install && npm run sync` after bumping versions in package.json.
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const pkgDir = (name) => path.join(root, 'node_modules', name);
const version = (name) => JSON.parse(fs.readFileSync(path.join(pkgDir(name), 'package.json'))).version;
const write = (rel, content) => {
    const file = path.join(root, rel);
    fs.mkdirSync(path.dirname(file), {recursive: true});
    fs.writeFileSync(file, content);
};

const ICONS = [
    'arrow-left', 'arrow-right', 'arrow-up-right', 'bars', 'calendar', 'check',
    'chevron-down', 'chevron-left', 'chevron-right', 'circle-check', 'circle-info',
    'circle-xmark', 'clock', 'code', 'copy', 'display', 'envelope', 'globe', 'house',
    'link', 'logo-github', 'logo-telegram', 'magnifier', 'moon', 'sun', 'tag',
    'triangle-exclamation', 'xmark',
];
const FONT_SUBSETS = ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext'];
const FONT_WEIGHTS = [400, 600];

function syncTokens() {
    const css = fs.readFileSync(path.join(pkgDir('@gravity-ui/uikit'), 'styles/styles.css'), 'utf8');
    const block = (selector) => {
        const start = css.indexOf(`\n${selector} {\n`);
        if (start < 0) throw new Error(`Selector not found: ${selector}`);
        const bodyStart = css.indexOf('{', start) + 1;
        const body = css.slice(bodyStart, css.indexOf('\n}', bodyStart));
        return body
            .split(/;\s*\n/)
            .map((decl) => decl.trim().replace(/\s*\n\s*/g, ' ').replace(/;$/, ''))
            .filter((decl) => decl.startsWith('--'));
    };
    const header = `// Generated by scripts/sync-vendor.mjs from @gravity-ui/uikit@${version('@gravity-ui/uikit')}.\n` +
        '// Copyright (c) 2021 YANDEX LLC, MIT License. Do not edit by hand.\n';
    const mixin = (name, decls) => `${header}\n@mixin ${name} {\n${decls.map((d) => `  ${d};`).join('\n')}\n}\n`;

    write('_sass/perigee/tokens/_common.scss', mixin('common', block('.g-root')));
    write('_sass/perigee/tokens/_light.scss', mixin('light', block('.g-root_theme_light')));
    write('_sass/perigee/tokens/_dark.scss', mixin('dark', block('.g-root_theme_dark')));
}

function syncIcons() {
    const dir = path.join(pkgDir('@gravity-ui/icons'), 'svgs');
    for (const name of ICONS) {
        const svg = fs.readFileSync(path.join(dir, `${name}.svg`), 'utf8')
            .trim()
            .replace('<svg ', '<svg aria-hidden="true" focusable="false" ')
            .replace(/ width="\d+" height="\d+"/, '');
        write(`_includes/icons/${name}.svg`, svg);
    }
    fs.copyFileSync(path.join(pkgDir('@gravity-ui/icons'), 'LICENSE'), path.join(root, '_includes/icons/LICENSE'));
}

function syncFonts() {
    const dir = pkgDir('@fontsource/inter');
    const faces = [];
    for (const weight of FONT_WEIGHTS) {
        const css = fs.readFileSync(path.join(dir, `${weight}.css`), 'utf8');
        for (const subset of FONT_SUBSETS) {
            const file = `inter-${subset}-${weight}-normal.woff2`;
            const range = css.match(new RegExp(`/\\* inter-${subset}-${weight}-normal \\*/[\\s\\S]*?unicode-range: ([^;]+);`))[1];
            fs.mkdirSync(path.join(root, 'assets/fonts/inter'), {recursive: true});
            fs.copyFileSync(path.join(dir, 'files', file), path.join(root, 'assets/fonts/inter', file));
            faces.push(`@font-face {\n  font-family: "Inter";\n  font-style: normal;\n  font-weight: ${weight};\n` +
                `  font-display: swap;\n  src: url("../fonts/inter/${file}") format("woff2");\n  unicode-range: ${range};\n}\n`);
        }
    }
    fs.copyFileSync(path.join(dir, 'LICENSE'), path.join(root, 'assets/fonts/inter/LICENSE.txt'));
    write('_sass/perigee/_fonts.scss',
        `// Generated by scripts/sync-vendor.mjs from @fontsource/inter@${version('@fontsource/inter')} (SIL OFL 1.1).\n\n${faces.join('\n')}`);
}

syncTokens();
syncIcons();
syncFonts();
console.log('Synced tokens, icons and fonts.');
